In [1]:
import re
import unicodedata
import numpy as np
import pandas as pd
import nltk

nltk.download("punkt", quiet=True)
from nltk.tokenize import wordpunct_tokenize

In [2]:
parallel_pairs = [
    ("मैं आज कॉलेज जा रहा हूँ।", "I am going to college today."),
    ("मेरा नाम राहुल है।", "My name is Rahul."),
    ("आज मौसम बहुत अच्छा है।", "The weather is very nice today."),
    ("मुझे किताबें पढ़ना पसंद है।", "I like reading books."),
    ("वह रोज़ सुबह दौड़ता है।", "He runs every morning."),
    ("हमने कल एक फिल्म देखी।", "We watched a movie yesterday."),
    ("कृपया दरवाज़ा बंद कर दीजिए।", "Please close the door."),
    ("भारत एक बड़ा देश है।", "India is a large country."),
    ("मुझे कंप्यूटर विज्ञान पसंद है।", "I like computer science."),
    ("वह अपनी परीक्षा की तैयारी कर रही है।", "She is preparing for her exam."),
    ("आज मेरी कक्षा जल्दी खत्म होगी।", "My class will finish early today."),
    ("हम रविवार को बाजार जाएंगे।", "We will go to the market on Sunday."),
    ("यह किताब बहुत उपयोगी है।", "This book is very useful."),
    ("मेरे दोस्त दिल्ली में रहते हैं।", "My friends live in Delhi."),
    ("मैं रोज़ Python सीखता हूँ।", "I learn Python every day."),
    ("कृपया मुझे पानी दीजिए।", "Please give me some water."),
    ("बच्चे पार्क में खेल रहे हैं।", "The children are playing in the park."),
    ("आज हमें एक प्रोजेक्ट पूरा करना है।", "We have to complete a project today."),
    ("वह ट्रेन से घर गया।", "He went home by train."),
    ("अच्छी नींद स्वास्थ्य के लिए जरूरी है।", "Good sleep is important for health.")
]

parallel_df = pd.DataFrame(parallel_pairs, columns=["Hindi", "English"])
parallel_df.index = range(1, len(parallel_df) + 1)
parallel_df.index.name = "Pair ID"

parallel_df

,Hindi,English
Pair ID,,
1,मैं आज कॉलेज जा रहा हूँ।,I am going to college today.
2,मेरा नाम राहुल है।,My name is Rahul.
3,आज मौसम बहुत अच्छा है।,The weather is very nice today.
4,मुझे किताबें पढ़ना पसंद है।,I like reading books.
5,वह रोज़ सुबह दौड़ता है।,He runs every morning.
6,हमने कल एक फिल्म देखी।,We watched a movie yesterday.
7,कृपया दरवाज़ा बंद कर दीजिए।,Please close the door.
8,भारत एक बड़ा देश है।,India is a large country.
9,मुझे कंप्यूटर विज्ञान पसंद है।,I like computer science.
10,वह अपनी परीक्षा की तैयारी कर रही है।,She is preparing for her exam.
11,आज मेरी कक्षा जल्दी खत्म होगी।,My class will finish early today.
12,हम रविवार को बाजार जाएंगे।,We will go to the market on Sunday.
13,यह किताब बहुत उपयोगी है।,This book is very useful.
14,मेरे दोस्त दिल्ली में रहते हैं।,My friends live in Delhi.
15,मैं रोज़ Python सीखता हूँ।,I learn Python every day.
16,कृपया मुझे पानी दीजिए।,Please give me some water.
17,बच्चे पार्क में खेल रहे हैं।,The children are playing in the park.
18,आज हमें एक प्रोजेक्ट पूरा करना है।,We have to complete a project today.
19,वह ट्रेन से घर गया।,He went home by train.
20,अच्छी नींद स्वास्थ्य के लिए जरूरी है।,Good sleep is important for health.

In [3]:
def tokenize_text(text):
    text = unicodedata.normalize("NFC", text)
    tokens = wordpunct_tokenize(text)
    return [t for t in tokens if any(ch.isalnum() for ch in t)]

parallel_df["Hindi Tokens"] = parallel_df["Hindi"].apply(tokenize_text)
parallel_df["English Tokens"] = parallel_df["English"].apply(tokenize_text)
parallel_df["Hindi Length"] = parallel_df["Hindi Tokens"].apply(len)
parallel_df["English Length"] = parallel_df["English Tokens"].apply(len)

parallel_df

,Hindi,English,Hindi Tokens,English Tokens,Hindi Length,English Length
Pair ID,,,,,,
1,मैं आज कॉलेज जा रहा हूँ।,I am going to college today.,"[मैं, आज, कॉलेज, जा, रहा, हूँ]","[I, am, going, to, college, today]",6,6
2,मेरा नाम राहुल है।,My name is Rahul.,"[मेरा, नाम, राहुल, है]","[My, name, is, Rahul]",4,4
3,आज मौसम बहुत अच्छा है।,The weather is very nice today.,"[आज, मौसम, बहुत, अच्छा, है]","[The, weather, is, very, nice, today]",5,6
4,मुझे किताबें पढ़ना पसंद है।,I like reading books.,"[मुझे, किताबें, पढ़ना, पसंद, है]","[I, like, reading, books]",5,4
5,वह रोज़ सुबह दौड़ता है।,He runs every morning.,"[वह, रोज़, सुबह, दौड़ता, है]","[He, runs, every, morning]",5,4
6,हमने कल एक फिल्म देखी।,We watched a movie yesterday.,"[हमने, कल, एक, फिल्म, देखी]","[We, watched, a, movie, yesterday]",5,5
7,कृपया दरवाज़ा बंद कर दीजिए।,Please close the door.,"[कृपया, दरवाज़ा, बंद, कर, दीजिए]","[Please, close, the, door]",5,4
8,भारत एक बड़ा देश है।,India is a large country.,"[भारत, एक, बड़ा, देश, है]","[India, is, a, large, country]",5,5
9,मुझे कंप्यूटर विज्ञान पसंद है।,I like computer science.,"[मुझे, कंप्यूटर, विज्ञान, पसंद, है]","[I, like, computer, science]",5,4
10,वह अपनी परीक्षा की तैयारी कर रही है।,She is preparing for her exam.,"[वह, अपनी, परीक्षा, की, तैयारी, कर, रही, है]","[She, is, preparing, for, her, exam]",8,6
11,आज मेरी कक्षा जल्दी खत्म होगी।,My class will finish early today.,"[आज, मेरी, कक्षा, जल्दी, खत्म, होगी]","[My, class, will, finish, early, today]",6,6
12,हम रविवार को बाजार जाएंगे।,We will go to the market on Sunday.,"[हम, रविवार, को, बाजार, जाएंगे]","[We, will, go, to, the, market, on, Sunday]",5,8
13,यह किताब बहुत उपयोगी है।,This book is very useful.,"[यह, किताब, बहुत, उपयोगी, है]","[This, book, is, very, useful]",5,5
14,मेरे दोस्त दिल्ली में रहते हैं।,My friends live in Delhi.,"[मेरे, दोस्त, दिल्ली, में, रहते, हैं]","[My, friends, live, in, Delhi]",6,5
15,मैं रोज़ Python सीखता हूँ।,I learn Python every day.,"[मैं, रोज़, Python, सीखता, हूँ]","[I, learn, Python, every, day]",5,5
16,कृपया मुझे पानी दीजिए।,Please give me some water.,"[कृपया, मुझे, पानी, दीजिए]","[Please, give, me, some, water]",4,5
17,बच्चे पार्क में खेल रहे हैं।,The children are playing in the park.,"[बच्चे, पार्क, में, खेल, रहे, हैं]","[The, children, are, playing, in, the, park]",6,7
18,आज हमें एक प्रोजेक्ट पूरा करना है।,We have to complete a project today.,"[आज, हमें, एक, प्रोजेक्ट, पूरा, करना, है]","[We, have, to, complete, a, project, today]",7,7
19,वह ट्रेन से घर गया।,He went home by train.,"[वह, ट्रेन, से, घर, गया]","[He, went, home, by, train]",5,5
20,अच्छी नींद स्वास्थ्य के लिए जरूरी है।,Good sleep is important for health.,"[अच्छी, नींद, स्वास्थ्य, के, लिए, जरूरी, है]","[Good, sleep, is, important, for, health]",7,6

In [4]:
# Basic one-to-one sentence alignment.
for pair_id, row in parallel_df.iterrows():
    print(f"Pair {pair_id}")
    print("Hindi  :", row["Hindi"])
    print("English:", row["English"])
    print()

Pair 1
Hindi  : मैं आज कॉलेज जा रहा हूँ।
English: I am going to college today.

Pair 2
Hindi  : मेरा नाम राहुल है।
English: My name is Rahul.

Pair 3
Hindi  : आज मौसम बहुत अच्छा है।
English: The weather is very nice today.

Pair 4
Hindi  : मुझे किताबें पढ़ना पसंद है।
English: I like reading books.

Pair 5
Hindi  : वह रोज़ सुबह दौड़ता है।
English: He runs every morning.

Pair 6
Hindi  : हमने कल एक फिल्म देखी।
English: We watched a movie yesterday.

Pair 7
Hindi  : कृपया दरवाज़ा बंद कर दीजिए।
English: Please close the door.

Pair 8
Hindi  : भारत एक बड़ा देश है।
English: India is a large country.

Pair 9
Hindi  : मुझे कंप्यूटर विज्ञान पसंद है।
English: I like computer science.

Pair 10
Hindi  : वह अपनी परीक्षा की तैयारी कर रही है।
English: She is preparing for her exam.

Pair 11
Hindi  : आज मेरी कक्षा जल्दी खत्म होगी।
English: My class will finish early today.

Pair 12
Hindi  : हम रविवार को बाजार जाएंगे।
English: We will go to the market on Sunday.

Pair 13
Hindi  : यह किताब बहुत उपयोगी है।
English: This book is very useful.

Pair 14
Hindi  : मेरे दोस्त दिल्ली में रहते हैं।
English: My friends live in Delhi.

Pair 15
Hindi  : मैं रोज़ Python सीखता हूँ।
English: I learn Python every day.

Pair 16
Hindi  : कृपया मुझे पानी दीजिए।
English: Please give me some water.

Pair 17
Hindi  : बच्चे पार्क में खेल रहे हैं।
English: The children are playing in the park.

Pair 18
Hindi  : आज हमें एक प्रोजेक्ट पूरा करना है।
English: We have to complete a project today.

Pair 19
Hindi  : वह ट्रेन से घर गया।
English: He went home by train.

Pair 20
Hindi  : अच्छी नींद स्वास्थ्य के लिए जरूरी है।
English: Good sleep is important for health.

In [5]:
hindi_tokens = [t for row in parallel_df["Hindi Tokens"] for t in row]
english_tokens = [t for row in parallel_df["English Tokens"] for t in row]

statistics = pd.DataFrame({
    "Language": ["Hindi", "English"],
    "Total Tokens": [len(hindi_tokens), len(english_tokens)],
    "Vocabulary Size": [len(set(hindi_tokens)), len(set(english_tokens))],
    "Average Sentence Length": [
        parallel_df["Hindi Length"].mean(),
        parallel_df["English Length"].mean()
    ]
})

statistics

  Language  Total Tokens  Vocabulary Size  Average Sentence Length
0    Hindi           109               81                     5.45
1  English           107               77                     5.35

In [6]:
code_mixed_sentences = [
    "आज मेरा Python assignment complete हो गया!",
    "कल college में presentation है।",
    "यह movie बहुत interesting है।",
    "मैंने आज नया laptop खरीदा।",
    "Please मुझे यह file send कर दो।",
    "आज gym के बाद coding करूंगा।",
    "मेरा internet आज बहुत slow है।",
    "इस project का deadline tomorrow है।",
    "तुमने मेरा message check किया?",
    "आज class में machine learning पढ़ी।"
]

code_mixed_df = pd.DataFrame({"Original": code_mixed_sentences})
code_mixed_df

                                     Original
0  आज मेरा Python assignment complete हो गया!
1             कल college में presentation है।
2               यह movie बहुत interesting है।
3                  मैंने आज नया laptop खरीदा।
4             Please मुझे यह file send कर दो।
5                आज gym के बाद coding करूंगा।
6              मेरा internet आज बहुत slow है।
7         इस project का deadline tomorrow है।
8              तुमने मेरा message check किया?
9         आज class में machine learning पढ़ी।

In [7]:
def normalize_code_mixed(text):
    text = unicodedata.normalize("NFC", text)
    text = re.sub(r"\s+", " ", text)
    text = re.sub(r"([!?.,])\1+", r"\1", text)
    return text.strip().lower()

code_mixed_df["Normalized"] = code_mixed_df["Original"].apply(
    normalize_code_mixed
)

code_mixed_df

,Original,Normalized
0,आज मेरा Python assignment complete हो गया!,आज मेरा python assignment complete हो गया!
1,कल college में presentation है।,कल college में presentation है।
2,यह movie बहुत interesting है।,यह movie बहुत interesting है।
3,मैंने आज नया laptop खरीदा।,मैंने आज नया laptop खरीदा।
4,Please मुझे यह file send कर दो।,please मुझे यह file send कर दो।
5,आज gym के बाद coding करूंगा।,आज gym के बाद coding करूंगा।
6,मेरा internet आज बहुत slow है।,मेरा internet आज बहुत slow है।
7,इस project का deadline tomorrow है।,इस project का deadline tomorrow है।
8,तुमने मेरा message check किया?,तुमने मेरा message check किया?
9,आज class में machine learning पढ़ी।,आज class में machine learning पढ़ी।

In [8]:
DEVANAGARI_RE = re.compile(r"[\u0900-\u097F]")
ROMAN_RE = re.compile(r"[A-Za-z]")

def identify_token(token):
    has_indic = bool(DEVANAGARI_RE.search(token))
    has_roman = bool(ROMAN_RE.search(token))

    if has_indic and has_roman:
        return "Mixed"
    elif has_indic:
        return "Indic"
    elif has_roman:
        return "Roman/English"
    return "Other"

for i, sentence in enumerate(code_mixed_df["Normalized"], 1):
    print(f"Sentence {i}: {sentence}")
    for token in tokenize_text(sentence):
        print(f"  {token} -> {identify_token(token)}")
    print("-" * 50)

Sentence 1: आज मेरा python assignment complete हो गया!
  आज -> Indic
  मेरा -> Indic
  python -> Roman/English
  assignment -> Roman/English
  complete -> Roman/English
  हो -> Indic
  गया -> Indic
--------------------------------------------------
Sentence 2: कल college में presentation है।
  कल -> Indic
  college -> Roman/English
  में -> Indic
  presentation -> Roman/English
  है -> Indic
--------------------------------------------------
Sentence 3: यह movie बहुत interesting है।
  यह -> Indic
  movie -> Roman/English
  बहुत -> Indic
  interesting -> Roman/English
  है -> Indic
--------------------------------------------------
Sentence 4: मैंने आज नया laptop खरीदा।
  मैंने -> Indic
  आज -> Indic
  नया -> Indic
  laptop -> Roman/English
  खरीदा -> Indic
--------------------------------------------------
Sentence 5: please मुझे यह file send कर दो।
  please -> Roman/English
  मुझे -> Indic
  यह -> Indic
  file -> Roman/English
  send -> Roman/English
  कर -> Indic
  दो -> Indic
--------------------------------------------------
Sentence 6: आज gym के बाद coding करूंगा।
  आज -> Indic
  gym -> Roman/English
  के -> Indic
  बाद -> Indic
  coding -> Roman/English
  करूंगा -> Indic
--------------------------------------------------
Sentence 7: मेरा internet आज बहुत slow है।
  मेरा -> Indic
  internet -> Roman/English
  आज -> Indic
  बहुत -> Indic
  slow -> Roman/English
  है -> Indic
--------------------------------------------------
Sentence 8: इस project का deadline tomorrow है।
  इस -> Indic
  project -> Roman/English
  का -> Indic
  deadline -> Roman/English
  tomorrow -> Roman/English
  है -> Indic
--------------------------------------------------
Sentence 9: तुमने मेरा message check किया?
  तुमने -> Indic
  मेरा -> Indic
  message -> Roman/English
  check -> Roman/English
  किया -> Indic
--------------------------------------------------
Sentence 10: आज class में machine learning पढ़ी।
  आज -> Indic
  class -> Roman/English
  में -> Indic
  machine -> Roman/English
  learning -> Roman/English
  पढ़ी -> Indic
--------------------------------------------------